### ISSUE TITLE
Is the executable tied to the data files?

### ISSUE THREAD

**Issue by enioluwas** [AthenaADP/MHW-ASS#11]
The Geralt, Ciri and Nergi gamma armor set data is now available in this repository but replacing the relevant text files in the `Data` folder of the released version v0.60b causes the executable to stop working. Am I doing something wrong or is the exe tied to that specific dataset for each release? In other words is the only way to incorporate new data to wait for another released version?

If there were developer setup instructions I would have dived into creating a dev build myself with updated data but without them it is a little bit more time consuming.

**Comment by AthenaADP** [comment]
The executable is not tied to the data files (other than the existing VERSION number in the settings file).

Probably you are missing the translations for the new stuff. I have made the app more robust by adding more diagnostic info popups if invalid data is found.
