### ISSUE TITLE
Gala Suit Armor data is partially incorrect.

### ISSUE THREAD

**Issue by Diskmaster** [AthenaADP/MHW-ASS#12]
HR 49+ (non-augmented, PC, no mods installed, currently at just before Tempered Kirin quest)
Also just checked the LR version, only the HR variant needs to be changed from 70 to 76 pre-agument.

![20190224141930_1](https://user-images.githubusercontent.com/146549/53304895-a9efc100-3872-11e9-9f58-4f630641fbb2.jpg)
![20190224141935_1](https://user-images.githubusercontent.com/146549/53304897-abb98480-3872-11e9-8fb5-73941af32313.jpg)
![20190224141937_1](https://user-images.githubusercontent.com/146549/53304898-aceab180-3872-11e9-9467-19eba0373e4a.jpg)
![20190224141940_1](https://user-images.githubusercontent.com/146549/53304902-ae1bde80-3872-11e9-9c88-ae7ad0d0c790.jpg)
![20190224141942_1](https://user-images.githubusercontent.com/146549/53304903-afe5a200-3872-11e9-9398-9194d0ab9110.jpg)

**Comment by AthenaADP** [comment]
Fixed, thanks!
