### ISSUE TITLE
Slows PC

### ISSUE THREAD

**Issue by AlbertoSoutullo** [AthenaADP/MHW-ASS#17]
I am having issues with v0.61v. Don't know why or how but it goes extremely laggy and makes my pc goes slow aswell.

Using it on Win 10. Anyone one having this issue?

**Comment by AthenaADP** [comment]
Which skills are you searching for? What settings? Do other versions have this issue? What about the just-released v0.62b?

**Comment by AthenaADP** [comment]
Closing as I cannot repro. Let me know if you have any further info.
