### ISSUE TITLE
Bug with right-click in results

### ISSUE THREAD

**Issue by Guzhuu** [AthenaADP/MHW-ASS#23]
In the options menu, if the jewel names are deactivated and a jewel is right clicked in the Results list, a System.FormatException will happen
![ss (2019-08-31 at 05 54 26)](https://user-images.githubusercontent.com/44607162/64066320-69557380-cc18-11e9-8b68-f737480123e6.png)
![ss (2019-08-31 at 05 54 37)](https://user-images.githubusercontent.com/44607162/64066321-69557380-cc18-11e9-9c6b-7350d0893fe4.png)

(First time I make an issue, dont know if this is enough)

**Comment by AthenaADP** [comment]
Thanks for the report. Have fixed!
