### ISSUE TITLE
Remove redundancies

### ISSUE THREAD

**Issue by khionu** [AthenaADP/MHW-ASS#7]
For example, you can search for "Razor Shot/Spare Shot" or "Xeno'jiiva Divinity lvl3". The latter restricts you in armour choices, but the former will include getting it through Xeno's armour (and getting less than Lvl 3 is pointless).

So, I'd recommend adjusting the parameters so there's only "Razor Shot/Spare Shot", as well as for any other skill/monster-skill pairs where this dynamic is true.

**Comment by AthenaADP** [comment]
Yeah, probably worth changing.

**Comment by AthenaADP** [comment]
Should be fixed now.
